modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="contentify"
version="1.11"
displayName="Contentify"
credits="Disketaa"
displayURL="https://www.curseforge.com/minecraft/mc-mods/contentify"
logoFile="logo.png"
authors="AnimeH"
description='''
Expand your true vanilla gameplay without nothing extra and outrageous! 🙌
'''

[[dependencies.contentify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.contentify]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

